environment:
  matrix:
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i npminstall && node_modules\.bin\npminstall

test_script:
  - node --version
  - npm --version
  # - set DEBUG=egg-ts-helper*,-not_this
  - npm run test

build: off
