// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/context';
declare module 'egg' {
  interface Context {
    ctx: typeof ExtendObject.ctx;
    isProd: typeof ExtendObject.isProd;
    isAjax: typeof ExtendObject.isAjax;
  }
}