// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/helper';
declare module '' {
  interface IHelper {
    isCool: typeof ExtendObject.isCool;
    isNotCool: typeof ExtendObject.isNotCool;
  }
}