// This file was auto generated by ts-helper
// Do not modify this file!!!!!!!!!

import ExtendObject from '../../../app/extend/application';
declare module 'larva' {
  interface Application {
    isCool: typeof ExtendObject.isCool;
    isNotCool: typeof ExtendObject.isNotCool;
  }
}